name: PR Target


on:
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
  assign-author-to-pr:
    uses: finleyfamily/workflows/.github/workflows/pr.assign-author.yml@master
  label-pr:
    name: Label PR
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6.0.0
        with:
          disable-releaser: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
